###############################################################################
###                           API Configuration                             ###
###############################################################################

[api]

# Enable defines if the API server should be enabled.
enable = true

# Swagger defines if swagger documentation should automatically be registered.
swagger = false

# Address defines the API server to listen on.
address = "tcp://20.231.58.174:1317"

# MaxOpenConnections defines the number of maximum open connections.
max-open-connections = 1000